unique_ids:
  assets:
    standard-page.html: QCWUT7Q2TOXQMQGSBTF4CZOERJJRIJOG
    theme.css: 5UE7HHBND2PG4MGOVIORQW4W3TBWNDCZ
  forms:
    Form1: '1732742022589517718189643.6789'
  modules: {}
  scripts: {}
  server_modules: {}
